### ISSUE TITLE
Integration issues for News team

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/bbc-a11y#12]
As originally reported by @sarafs in #11.

1) features/02_validation.feature View
Scenario: Submit to W3C validation Service
See http://validator.w3.org
When I submit the page to the W3C Markup Validation Service
Then there should be no errors
Note: Any site invariably always fails for the W3C validator

2) Heading hierarchy tests are failing -
Then(/^each heading must be followed by content or a heading of one level deeper (h2-h6)$/) do
puts "Heading hierarchy:"
puts page.heading_hierarchy.to_s
page.must_have_correct_heading_hierarchy

Note: from this spec heading_hierarchy_spec.rb the HeadingHierarchy module returns an invalid Xpath error.

3) def must_have_title_that_contains_h1_text
expect(browser.title).to include(browser.find('h1').text)
Note: Fails due to a miss-match in Page Title and h1 text

4) Scenario: View the page with JavaScript and CSS disabled
When I view the page with JavaScript and CSS disabled
Then all core content is available and functional
Note: Manual test

**Comment by mattwynne** [comment]
@sarafs are any of these issues still relevant after today's session?

**Comment by sarafs** [comment]
@mattwynne these are the failures I see -

URL: http://www.bbc.co.uk/mundo & http://m.live.bbc.co.uk/news
1)   - Scenario: Check headings ✗

Unable to find xpath "/html/head/meta/meta/meta/meta/meta/meta/link/meta/link/link/link/link/link/meta/meta/meta/meta/meta/meta/meta/meta/link/link/link/link/body/div/div[3]/div/div/section/div/div/h2"
/Users/sarafs02/.gem/ruby/2.0.0/gems/capybara-2.4.4/lib/capybara/node/finders.rb:41:in `block in find'
/Users/sarafs02/.gem/ruby/2.0.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
/Users/sarafs02/.gem/ruby/2.0.0/gems/capybara-2.4.4/lib/capybara/node/finders.rb:30:in `find'
/Users/sarafs02/.gem/ruby/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'
/Library/Ruby/Gems/2.0.0/gems/bbc-a11y-0.0.4/lib/bbc/a11y/cucumber_support/heading_hierarchy.rb:53:in `block in heading_elements'
/Library/Ruby/Gems/2.0.0/gems/bbc-a11y-0.0.4/lib/bbc/a11y/cucumber_support/heading_hierarchy.rb:52:in `map'
/Library/Ruby/Gems/2.0.0/gems/bbc-a11y-0.0.4/lib/bbc/a11y/cucumber_support/heading_hierarchy.rb:52:in `heading_elements'
/Library/Ruby/Gems/2.0.0/gems/bbc-a11y-0.0.4/lib/bbc/a11y/cucumber_support/heading_hierarchy.rb:45:in `headings'
/Library/Ruby/Gems/2.0.0/gems/bbc-a11y-0.0.4/lib/bbc/a11y/cucumber_support/heading_hierarchy.rb:30:in `to_s'
/Library/Ruby/Gems/2.0.0/gems/bbc-a11y-0.0.4/features/step_definitions/page_steps.rb:32:in `/^each heading must be followed by content or a heading of one level deeper \(h2\-h6\)$/'

2) URL: http://m.live.bbc.co.uk/news ( I have used 'm.live' instead of  'm.' as it forces the mobile site to load for the tests. 'm.' redirects to 'www' on desktop browser widths)
This looks more like a genuine accessibility issue on the page. @IanPouncey could you please confirm.
(On the page in 2nd column the Most - Read tab - 'most-popular__header__tabs--read open' has tabindex="0").

Correctly use `tabindex` attributes
-----------------------------------

  - Scenario: Check all tabindex values ✗

expected `[#<Capybara::Element tag="a">].empty?` to return true, got false
/Library/Ruby/Gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/fail_with.rb:29:in `fail_with'
/Library/Ruby/Gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:40:in `handle_failure'
/Library/Ruby/Gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
/Library/Ruby/Gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
/Library/Ruby/Gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
/Library/Ruby/Gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
/Library/Ruby/Gems/2.0.0/gems/bbc-a11y-0.0.4/lib/bbc/a11y/cucumber_support/page.rb:62:in `must_not_have_any_positive_tabindex_values'
/Library/Ruby/Gems/2.0.0/gems/bbc-a11y-0.0.4/features/step_definitions/page_steps.rb:45:in `/^there should be no elements with a tabindex attribte of 0 or greater$/'

**Comment by mattwynne** [comment]
Closed in favour of #20 and #21
