### ISSUE TITLE
Switch to using json for config

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/bbc-a11y#60]
So it will work for a JS linter

**Comment by mattwynne** [comment]
#57 is related.

**Comment by joshski** [comment]
I'm not sure about this any more.

JSON means a whole lot boilerplate than Ruby for the very basic cases, and the runner is in Ruby. Also you can't do anything dynamic in JSON, which is why I think we struggled to find the right shape for this new configuration when we had a little play with this idea.

We know that testing a single page in a browser is useful, but we haven't established that running a whole suite in a browser is possible yet. IMO we should spike running a whole suite in a browser before doing this.

**Comment by mattwynne** [comment]
Ok sounds sensible. Let's defer this for now. Shall we just close the
ticket? We're hardly likely to forget the idea.

**Comment by joshski** [comment]
Yep let's close for now
